#ifndef COMMON_H_
#define COMMON_H_

#define AVG_BLUR_MIN_SIZE 1
#define AVG_BLUR_MAX_SIZE 30

#define GAUSSIAN_BLUR_MIN_SIZE 1
#define GAUSSIAN_BLUR_MAX_SIZE 41
#define GAUSSIAN_BLUR_SIGMAX 40
#define GAUSSIAN_BLUR_SIGMAY 40

#define MEDIAN_BLUR_MAX 81

#define BILATERAL_BLUR_MAX_SIZE 100
#define BILATERAL_BLUR_MAX_COLOR 255
#define BILATERAL_BLUR_MAX_SPACE 300


#endif